### ISSUE TITLE
Zoomed text in Confirmation page pattern

### ISSUE THREAD

**Issue by philsherry** [hmrc/accessibility#20]
GOV.UK Design System’s [Confirmation pages](https://design-system.service.gov.uk/patterns/confirmation-pages/) [pattern](https://github.com/alphagov/govuk-design-system-backlog/issues/40) has issues when a user sets their browser font size to 200% on iOS. 

![words poking out the confirmation box](https://user-images.githubusercontent.com/272769/82329510-53bbf000-99d9-11ea-8c4a-128de706ac17.png)

**Comment by adamliptrot-oc** [comment]
Panel padding reduced and wrapping added as part of Gov UK Frontend v3.14.0
https://github.com/alphagov/govuk-frontend/releases/tag/v3.14.0
