### ISSUE TITLE
Voiceover and Voice Control on iPad iOS13.6.x Currency input component

### ISSUE THREAD

**Issue by adamliptrot-oc** [hmrc/accessibility#42]
## Voiceover 
It seems there is a bug in Voiceover for iOS 13.6 (issue continues on iOS 13.7) on iPads (not on iPhones) which means you can’t edit a currency field which has been pre-filled by **tapping on the input** (tapping on the label, or using the next/prev keyboard input navigation works).

iPad running iOS12.4 works as expected.
iPhones running iOS13.6 works as expected.

Empty currency fields are working as expected, but pre-filled ones are not editable.
The field is announced along with the contents and instructions to "double-tap to edit" but doing so just repeats the label.

## Voice control
The above seems to also be the case when using voice control to access the fields. **(seems fixed on iPad OS14)**

## To test
Test cases https://accessibility-training.herokuapp.com/examples/currency

A potential fix seems to be to add

```
.hmrc-currency-input__unit {
    pointer-events: none;
}
```

which allows pass-through on the £ symbol.

Audit board to track testing of fix: https://github.com/hmrc/accessibility-audits-external/projects/29

**Comment by adamliptrot-oc** [comment]
Fix added to HMRC Frontend

**Comment by chrismoorembe** [comment]
Do you know if this is still an issue with iOS 14?

**Comment by adamliptrot-oc** [comment]
@chrismoorembe Yes on iPad it is still an issue for Voiceover on iOS 14.0.1
